name: goscrum
stage: prod
myWebsite:
  component: "@serverless/website"
  inputs:
    code:
      root: ./ # The root folder of your website project.  Defaults to current working directory
      src: ./build # The folder to be uploaded containing your built artifact
      hook: yarn run build:dev # A hook to build/test/do anything to your code before uploading
    region: ap-south-1 # The AWS region to deploy your website into
    bucketName: goscrum-website
#    domain: goscrum.io
